[[coins]]
name = "Blackcoin"
ticker = "BLK"
api = "Chainz"
addresses = ["B7hAb7hDY8YkGrcQpYV1ig7nygVznBaBta", "BF58Wm7hXSPXxfXm6HwrkWAr45qrZhNHJu"]

[[coins]]
name = "Blacknet"
ticker = "BLN"
api = "Blnscan"
addresses = ["blacknet17tuwsx4twcl6ysjaj5pag03n59e56y37yagxht0rhmldl07yyxps6fhfjn"]
